spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springbatchnewversion
    password: postgresql
    username: postgres

  jpa:
    hibernate:
      ddl-auto : update
    properties:
      hibernate:
        show_sql : true

  batch:
    initialize-schema: always
    jdbc :
      initialize-schema: always

#  spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.format_sql=true
# spring.batch.jdbc.initialize-schema=always