INSERT INTO MY_APP_ITEM (NAME, VALUE_LONG1, VALUE_LONG2, VALUE_STR) VALUES('in1', 1, 1, 'un');
INSERT INTO MY_APP_ITEM (NAME, VALUE_LONG1, VALUE_LONG2, VALUE_STR) VALUES('in2', 2, 2, 'deux');
INSERT INTO MY_APP_ITEM (NAME, VALUE_LONG1, VALUE_LONG2, VALUE_STR) VALUES('in3', 3, 3, 'trois');
INSERT INTO MY_APP_ITEM (NAME, VALUE_LONG1, VALUE_LONG2, VALUE_STR) VALUES('in4', 4, 4, 'quatre');
INSERT INTO MY_APP_ITEM (NAME, VALUE_LONG1, VALUE_LONG2, VALUE_STR) VALUES('in5', 5, 5, 'cinq');
INSERT INTO MY_APP_ITEM (NAME, VALUE_LONG1, VALUE_LONG2, VALUE_STR) VALUES('in6', 6, 6, 'six');
INSERT INTO MY_APP_ITEM (NAME, VALUE_LONG1, VALUE_LONG2, VALUE_STR) VALUES('in7', 7, 7, 'sept');
